### ISSUE TITLE
Docs: Repository Docs for Setting up MySQL Backend

### ISSUE THREAD

**Issue by misslame** [LetsMesh/ProjectHub#15]
- Include docs in local set up for setting up local repository. Ensure all steps are one by one from when cloneing and easy for someone who hasn't used MySQL before to use. 

Bonus points if it includes MySQL workbench steps.

**Comment by 392781** [comment]
Y'all should consider using Docker containers instead of setup instructions so that local setup is OS/hardware agnostic *and* done automatically with minimal user input.  Docker also integrates very nicely with VS Code.
